{
  "openapi" : "3.0.0",
  "info" : {
    "title" : "",
    "description" : "",
    "version" : "1.0.0"
  },
  "servers" : [ {
    "url" : "https://watsonx.dragons.com",
    "description" : "watson challenge"
  } ],
  "paths" : { },
  "components" : { }
}